version: '3.8'

services:
    frontend:
    build: ./frontend
    container_name: synthetic_frontend_ts
    ports:
      - "3000:3000"
    networks:
      - synthetic_net

networks:
  synthetic_net:
    driver: bridge